### PR TITLE
correct multistream decompression EOF handling (fix #61)

### LINKED ISSUE #61: Filesize mismatch when decompressing multi-stream with sizes greater than 2GB (2^31)
Here is a self contained reproducer of the problem: [bzip_bug.zip](https://github.com/alexcrichton/bzip2-rs/files/4919986/bzip_bug.zip)

To reproduce:
```
unzip bzip_bug.zip
cd bzip_bug
cargo run --release --bin bzip_bug
```

You will see the following output:

```
$ cargo run --release --bin bzip_bug
   Compiling pkg-config v0.3.18
   Compiling libc v0.2.72
   Compiling cc v1.0.58
   Compiling bzip2-sys v0.1.9+1.0.8
   Compiling bzip2 v0.4.1
   Compiling bzip_bug v0.1.0 (/private/tmp/foo/bzip_bug)
    Finished release [optimized] target(s) in 9.08s
     Running `target/release/bzip_bug`
Generating expected results
Decompressing stream made with bzip2
Decompressing stream made with pbzip2
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `405900000`,
 right: `3000000000`: decompressed length mismatch', src/main.rs:37:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The expected output is that the program complete's sucessfully

The test has two files:
1. raw.dat.bz2 is a 3GB generated file produced using the `bzip2` tool on a mac
2. raw.dat.pbz2 is the same 3GB generated file produced using the `pbzip2` tool on a mac

The data was generated using the generate.rs tool in the package, via the following commands:
```
$ cargo build --release --all
$ ./target/release/generate | nice bzip2 > raw.dat.bz2&
$ ./target/release/generate | nice pbzip2 > raw.dat.pbz2&
```

You can check the output byte counts using `bzcat`:
```
$ bzcat raw.dat.bz2 | wc -c
  3000000000
```

```
$ bzcat raw.dat.pbz2 | wc -c
 3000000000
```

The issue seems to affect files that are larger than 2^31 (which smells like a u32 overflow somewhere)

### PR DESCRIPTION
**Pull request by afflux**
Still missing a good test case for this. I don't think the reproducer in #61 is a good candidate as it takes a long time to run. I should be able to reduce it to a smaller test in the next few days.

### CODE REVIEW

**Comment by alamb** [comment]
❤️  Nice @afflux 👍

**Comment by afflux** [comment]
regression test case added. It should be possible to reduce the size further if we changed the buffer size down from 8k to maybe 64 bytes, but this occurred to me only later. Let me know if you want me to do that.

**Comment by alexcrichton** [comment]
Thanks for this!

**Comment by alamb** [comment]
Thanks @afflux  @alexcrichton 

I re-ran the reproducer from #61 locally with `bzip2 = "0.4.2"` and it no longer errors. Thus from my perspective this PR fixed the issue as well. 🥇

**Pull request merged**
