### PR TITLE
[bzip2-sys] use the system bzip2 if found via pkg-config

### PR DESCRIPTION
**Pull request by michel-slm**
Similar approach to libz-sys: https://github.com/rust-lang/libz-sys/blob/master/build.rs

Signed-off-by: Michel Alexandre Salim <michel@michel-slm.name>

---
This change is [Reviewable](https://reviewable.io/reviews/alexcrichton/bzip2-rs/58)

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like rustfmt is failing? Otherwise seems reasonable!

**Comment by michel-slm** [comment]
Ah, let me fix that, thanks for flagging!

**Comment by michel-slm** [comment]
tested by building the upcoming Fedora RPM that includes this patch in Mock, with the bundled bzip2 stripped; it builds fine if the development headers for bzip2 are found via pkgconfig

https://salimma.fedorapeople.org/specs/rust/rust-bzip2-sys-0.1.8+1.0.8-1.fc32.src.rpm

**Comment by BusyJay** [comment]
This is clearly a breaking changes for dependents that expect to link bzip2 statically.

**Pull request merged**
